# Ensure the gradle wrapper in the repository has not been tampered with.
# If this check fails, something is seriously wrong -- try creating a new
# wrapper from a local gradle install.

name: validate gradle wrapper

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
